trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AppSecrets 
  - name: webAppName
    value: 'PipelineAPI'
  - name: azureServiceConnection
    value: 'Azure subscription 1 (e26f51cc-2002-4eef-9131-5841b18763a7)' 
  - name: resourceGroupName
    value: 'pipelineautomationapi'
  # SonarCloud Configuration for Azure Repos
  - name: sonarCloudConn
    value: 'SonarCloudConnection'
  - name: sonarOrg
    value: 'manoharankarthikeyan7-beep'
  - name: sonarProjectKey
    value: 'manoharankarthikeyan7-beep_Pipeline-automation'

stages:
- stage: Build
  displayName: 'Build and Security Scan'
  jobs:
  - job: Build_All
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    # Prepare for Azure Repo Scan
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: '$(sonarCloudConn)'
        organization: '$(sonarOrg)'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(sonarProjectKey)'
        cliProjectName: 'Pipeline-automation'
        cliSources: 'backend'
        extraProperties: |
          sonar.scm.provider=git
          sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
          sonar.exclusions=**/node_modules/**,**/frontend/build/**

    - script: |
        cd backend
        npm install
      displayName: 'Install Backend'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - script: |
        mkdir -p backend/public
        cp -r frontend/build/* backend/public/
      displayName: 'Merge Frontend to Backend'

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud Analysis'

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publish Quality Gate Result'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'backend'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployWeb
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: 'webAppLinux'
        appName: $(webAppName)
        resourceGroupName: $(resourceGroupName)
        package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
        runtimeStack: 'NODE|18-lts'